version: '3.8'

services:
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/:/usr/src/app/
#     - media_volume:/usr/src/app/api/mediafiles ---- saving in proj dir (not in container)
      - media_volume:/home/app/mediafiles  #   saving images in cont
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=post
      - POSTGRES_PASSWORD=gres
      - POSTGRES_DB=gym_dev
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

volumes:
  postgres_data:
  media_volume:
