version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/api/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/api/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - api
      - web


volumes:
  postgres_data:
  static_volume:
